<?php
/**
 * @var \Magestat\SplitOrder\Block\Checkout\Success $block
 */

$orderArray = $block->getOrderArray();

// @codingStandardsIgnoreFile
?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($orderArray):?>
            <p><?= /* @escapeNotVerified */ __('Your orders number are:');?></p>
            <ul>
            <?php foreach ($orderArray as $order => $incremental): ?>
                <?php if ($block->getCanViewOrder()) :?>
                    <li><?= sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $this->getUrl('sales/order/view/', ['order_id' => $order]), $block->escapeHtml($incremental)) ?></li>
                <?php else :?>
                    <li><?= $block->escapeHtml($incremental) ?></li>
                <?php endif;?>
            <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <?php if ($block->getCanViewOrder()) :?>
                <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
            <?php else: ?>
                <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
            <?php endif;?>
        <?php endif; ?>
            <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
